---
# path
_format:
  $ref: './path/_format.yaml'

id:
  $ref: './path/id.yaml'

sku:
  $ref: './path/sku.yaml'

# header
accept:
  $ref: './header/accept.yaml'

# query
isoCode:
  $ref: './query/filters/isoCode.yaml'

page:
  $ref: './query/filters/page.yaml'

pageSize:
  $ref: './query/filters/pageSize.yaml'

moduleName:
  $ref: './query/filters/moduleName.yaml'

platform:
  $ref: './query/filters/platform.yaml'

platformVersion:
  $ref: './query/filters/platformVersion.yaml'
